#!/bin/bash
source /usr/lib/naylib

draw_heading "Update/install pip packages"
# pip dependencies
sudo -v
draw_spinner "Installing \"termdown\"" "sudo pip install termdown"

dpkg -s "x11proto-xext-dev" &>/dev/null || sudo apt install -y x11proto-xext-dev &> /dev/null
dpkg -s "libxres-dev" &>/dev/null || sudo apt install -y libxres-dev &> /dev/null
dpkg -s "libx11-dev" &>/dev/null || sudo apt install -y libx11-dev &> /dev/null

sudo -v
draw_spinner "Installing \"ueberzug\"" "sudo pip install ueberzug"

sudo -v
draw_spinner "Installing \"oauth2-client\"" "sudo pip3 install oauth2-client"

sudo -v
draw_spinner "Installing \"apt-select\"" "sudo pip install apt-select"

# apt packages adjustments
## bat 
### install force
if ! dpkg -s "bat" &>/dev/null ; then
  cd /tmp
  apt-get download bat
  sudo apt install -y libgit2-28 
  sudo dpkg --force-overwrite -i bat*.deb
fi
sudo ln -sf /bin/batcat /bin/bat
